server:
    port: 8888

spring:
    security:
        user:
            name: cloud-user
            password: password
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Abacode7/rates-config
                    search-paths: ["station*"]
                    repos:
                        perf:
                            pattern: '*/perf'
                            uri: https://github.com/Abacode7/perf-config
                            search-paths: ["station*"]